# Generated by Django 4.2.10 on 2024-03-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('name_en', models.CharField(max_length=45, unique=True, verbose_name='英文')),
                ('phonetic_symbol', models.CharField(max_length=45, verbose_name='音标')),
                ('part_of_speech', models.CharField(max_length=20, verbose_name='词性')),
                ('name_zh', models.CharField(max_length=20, verbose_name='中文')),
            ],
            options={
                'verbose_name': 'a开头的单词',
                'verbose_name_plural': 'a开头的单词',
                'db_table': 'tb_a',
            },
        ),
    ]
