# Generated by Django 4.2.10 on 2024-03-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worda',
            name='name_en',
            field=models.CharField(db_comment='英文', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='worda',
            name='name_zh',
            field=models.CharField(db_comment='中文', max_length=20),
        ),
        migrations.AlterField(
            model_name='worda',
            name='part_of_speech',
            field=models.CharField(db_comment='词性', max_length=20),
        ),
        migrations.AlterField(
            model_name='worda',
            name='phonetic_symbol',
            field=models.CharField(db_comment='音标', max_length=45),
        ),
    ]
