# Generated by Django 4.2.10 on 2024-03-03 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_worda_name_en_alter_worda_name_zh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worda',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='worda',
            name='update_date',
        ),
        migrations.AddField(
            model_name='worda',
            name='create_at',
            field=models.DateTimeField(db_comment='创建日期', default=datetime.datetime(2024, 3, 3, 2, 42, 59, 13894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='worda',
            name='update_at',
            field=models.DateTimeField(db_comment='更新日期', default=datetime.datetime(2024, 3, 3, 2, 42, 59, 13911, tzinfo=datetime.timezone.utc)),
        ),
    ]
