# Generated by Django 4.2.10 on 2024-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_remove_worda_create_date_remove_worda_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worda',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='worda',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
    ]
